AllCops:
  # 除外するディレクトリ（自動生成されたファイル）
  # デフォルト設定にある"vendor/**/*"が無効化されないように記述
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
  # Rails向けのRails copsを実行。"rubocop -R"と同じ
Rails:
  Enabled: true

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

# "Prefer single-quoted strings when you don't need string interpolation or special symbols."を無効
Style/StringLiterals:
  Enabled: false

# "Line is too long"を無効
Metrics/LineLength:
  Enabled: false

# Missing magic comment # frozen_string_literal: true.を無効
Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/UnneededInterpolation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false
